"""index order items by order

Revision ID: 8cb49ddbd76d
Revises: 9c09e2beecdd
Create Date: 2026-08-30 14:53:51.220117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb49ddbd76d'
down_revision: Union[str, Sequence[str], None] = '9c09e2beecdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    # ### end Alembic commands ###
