"""index user order history

Revision ID: 96b1586a17cf
Revises: 323e7b9db92f
Create Date: 2026-08-30 14:47:31.150868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b1586a17cf'
down_revision: Union[str, Sequence[str], None] = '323e7b9db92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_user_created_at_id', 'orders', ['user_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_user_created_at_id', table_name='orders')
    # ### end Alembic commands ###
